name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  ManualWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "This is a manually triggered workflow!"
